name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: Run typing check
        run: pipenv run test-typing

      - name: Run format check
        run: pipenv run test-format
